FROM openjdk:17-jdk-slim
RUN mkdir -p /var/app
WORKDIR /var/app
COPY . .
RUN ./gradlew build
ARG JAR_FILE=./build/libs/api-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-Dspring.profiles.active=dev", "-Duser.timezone=Asia/Seoul", "-jar", "./build/libs/api-0.0.1-SNAPSHOT.jar"]